from __future__ import annotations

from app.services.stock_rule_contracts import (
    LEVEL_CAUTIOUS,
    LEVEL_NEUTRAL,
    LEVEL_POSITIVE,
    LEVEL_RISK,
    LEVEL_SORT_RANK,
    LEVEL_WATCH,
    QUALITY_GATE_CLOSE_CONFIDENCE_FLOOR,
    QUALITY_GATE_CLOSE_PENALTY,
    QUALITY_GATE_MATCHED_CONFIDENCE_FLOOR,
    QUALITY_GATE_MATCHED_PENALTY,
    QUALITY_GATE_MISSED_CONFIDENCE_FLOOR,
    QUALITY_GATE_MISSED_PENALTY,
    QUALITY_GATE_PASS_SCORE,
    QUALITY_GATE_RISK_MULTIPLIER,
    QUALITY_GATE_WEAK_SCORE,
    RULE_CONFIDENCE,
    RULE_VERSION as RULE_VERSION,
    SCORE_VERSION as SCORE_VERSION,
    STATUS_CLOSE,
    STATUS_MATCHED,
    STATUS_MISSED,
    STATUS_SORT_RANK,
    BreakMa20State,
    FundTechDivergenceState,
    HighValuationChaseState,
    QualityGateContext,
    QualityGateDecision,
    RuleMatchContext,
    RuleParameter,
    RuleSpec,
    SupportReboundState,
    VolumeBreakoutState,
)
from app.services.stock_rule_flow import (
    _rule_fund_tech_divergence as _rule_fund_tech_divergence,
    _rule_support_rebound as _rule_support_rebound,
)
from app.services.stock_rule_price import (
    _rule_break_ma20 as _rule_break_ma20,
    _rule_volume_breakout as _rule_volume_breakout,
)
from app.services.stock_rule_quality import _apply_quality_gate as _apply_quality_gate
from app.services.stock_rule_registry import (
    RULE_CONFIG as RULE_CONFIG,
    RULE_SPEC_BY_ID,
    RULE_SPECS as RULE_SPECS,
    RULE_SORT_INDEX,
    _raw_rule_matches as _raw_rule_matches,
    _rule_match_context as _rule_match_context,
    _rule_sort_key as _rule_sort_key,
    _sorted_rule_matches as _sorted_rule_matches,
    build_rule_match_summary as build_rule_match_summary,
    rule_definitions as rule_definitions,
)
from app.services.stock_rule_risk import (
    _rule_abnormal_risk as _rule_abnormal_risk,
    _rule_high_valuation_chase as _rule_high_valuation_chase,
)
from app.services.stock_rule_values import _rule_confidence as _rule_confidence


_COMPAT_REEXPORTS = (
    LEVEL_CAUTIOUS,
    LEVEL_NEUTRAL,
    LEVEL_POSITIVE,
    LEVEL_RISK,
    LEVEL_SORT_RANK,
    LEVEL_WATCH,
    QUALITY_GATE_CLOSE_CONFIDENCE_FLOOR,
    QUALITY_GATE_CLOSE_PENALTY,
    QUALITY_GATE_MATCHED_CONFIDENCE_FLOOR,
    QUALITY_GATE_MATCHED_PENALTY,
    QUALITY_GATE_MISSED_CONFIDENCE_FLOOR,
    QUALITY_GATE_MISSED_PENALTY,
    QUALITY_GATE_PASS_SCORE,
    QUALITY_GATE_RISK_MULTIPLIER,
    QUALITY_GATE_WEAK_SCORE,
    RULE_CONFIG,
    RULE_CONFIDENCE,
    RULE_SORT_INDEX,
    RULE_SPEC_BY_ID,
    RULE_SPECS,
    RULE_VERSION,
    SCORE_VERSION,
    STATUS_CLOSE,
    STATUS_MATCHED,
    STATUS_MISSED,
    STATUS_SORT_RANK,
    BreakMa20State,
    FundTechDivergenceState,
    HighValuationChaseState,
    QualityGateContext,
    QualityGateDecision,
    RuleMatchContext,
    RuleParameter,
    RuleSpec,
    SupportReboundState,
    VolumeBreakoutState,
    _apply_quality_gate,
    _raw_rule_matches,
    _rule_abnormal_risk,
    _rule_break_ma20,
    _rule_confidence,
    _rule_fund_tech_divergence,
    _rule_high_valuation_chase,
    _rule_match_context,
    _rule_sort_key,
    _rule_support_rebound,
    _rule_volume_breakout,
    _sorted_rule_matches,
    build_rule_match_summary,
    rule_definitions,
)
