"""Shared version identifiers for paper-trading contracts."""

DEFAULT_PAPER_ACCOUNT_NAME = "本地模拟账户"
DEFAULT_PAPER_INITIAL_CASH = 1_000_000.0
MODELLED_ONE_WAY_FRICTION_PCT = 0.05
PAPER_TRADING_RULE_VERSION = "paper-review-plan-v2"

__all__ = [
    "DEFAULT_PAPER_ACCOUNT_NAME",
    "DEFAULT_PAPER_INITIAL_CASH",
    "MODELLED_ONE_WAY_FRICTION_PCT",
    "PAPER_TRADING_RULE_VERSION",
]
