from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
ROUTES_DIR = ROOT / "app" / "api" / "routes"
OUTPUT = ROOT / "docs" / "API_REFERENCE.md"
METHODS = {"get", "post", "patch", "delete", "put"}


@dataclass(frozen=True)
class Endpoint:
    method: str
    path: str
    handler: str
    response_model: str
    file: str


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    endpoints = collect_endpoints()
    OUTPUT.write_text(render(endpoints), encoding="utf-8")


def collect_endpoints() -> list[Endpoint]:
    endpoints: list[Endpoint] = []
    for path in sorted(ROUTES_DIR.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        rel = str(path.relative_to(ROOT))
        endpoints.extend(route_decorator_endpoints(tree, rel))
        endpoints.extend(stock_registry_endpoints(tree, rel))
    return sorted(endpoints, key=lambda item: (item.path, item.method))


def route_decorator_endpoints(tree: ast.Module, rel: str) -> list[Endpoint]:
    endpoints: list[Endpoint] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            parsed = parse_route_decorator(decorator)
            if parsed is None:
                continue
            method, path, response_model = parsed
            endpoints.append(Endpoint(method, path, node.name, response_model, rel))
    return endpoints


def parse_route_decorator(node: ast.expr) -> tuple[str, str, str] | None:
    if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Attribute):
        return None
    if node.func.attr not in METHODS:
        return None
    if not isinstance(node.func.value, ast.Name) or node.func.value.id not in {"router", "app"}:
        return None
    if not node.args or not isinstance(node.args[0], ast.Constant) or not isinstance(node.args[0].value, str):
        return None
    response_model = "-"
    for keyword in node.keywords:
        if keyword.arg == "response_model":
            response_model = ast.unparse(keyword.value)
            break
    return node.func.attr.upper(), node.args[0].value, response_model


def stock_registry_endpoints(tree: ast.Module, rel: str) -> list[Endpoint]:
    endpoints: list[Endpoint] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.For):
            continue
        if not isinstance(node.iter, ast.List):
            continue
        for item in node.iter.elts:
            if not isinstance(item, ast.Tuple) or len(item.elts) < 3:
                continue
            path_node, model_node, handler_node = item.elts[:3]
            if not isinstance(path_node, ast.Constant) or not isinstance(path_node.value, str):
                continue
            endpoints.append(
                Endpoint(
                    "GET",
                    path_node.value,
                    ast.unparse(handler_node),
                    ast.unparse(model_node),
                    rel,
                )
            )
    return endpoints


def render(endpoints: list[Endpoint]) -> str:
    lines = [
        "# API Reference",
        "",
        "This file is generated by `$PYTHON tools/api_inventory.py` from FastAPI route declarations.",
        "Dynamic stock endpoints registered in `app/api/routes/stock.py` are included from the route registry list.",
        "The UI root route `/` is served from `app/main.py` and intentionally excluded from this business API reference.",
        "",
        "## Summary",
        "",
        f"Total endpoints: {len(endpoints)}",
        "",
        "| Method | Path | Handler | Response model | File |",
        "| --- | --- | --- | --- | --- |",
    ]
    for endpoint in endpoints:
        lines.append(
            f"| {endpoint.method} | `{endpoint.path}` | `{endpoint.handler}` | `{escape(endpoint.response_model)}` | `{endpoint.file}` |"
        )
    lines.extend(
        [
            "",
            "## API Design Notes",
            "",
            "- Route handlers should stay thin: validate parameters, call workflow/service functions, and return response models.",
            "- All user-facing failures should pass through `app/api/errors.py` or explicit `HTTPException` with Chinese messages.",
            "- New endpoints should be added to the relevant route module and this file should be regenerated.",
            "- Prefer `GET /api/stock/workbench` for frontend workbench loading to avoid repeated provider calls.",
            "",
        ]
    )
    return "\n".join(lines)


def escape(value: str) -> str:
    return value.replace("|", "\\|")


if __name__ == "__main__":
    main()
