from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "FUNCTION_INVENTORY.md"
SOURCE_DIRS = ("app", "tests", "tools")


@dataclass(frozen=True)
class Symbol:
    kind: str
    name: str
    line: int
    signature: str


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_inventory(), encoding="utf-8")


def build_inventory() -> str:
    sections = [
        "# Function Inventory",
        "",
        "This file is generated by `$PYTHON tools/architecture_inventory.py`.",
        "It is intentionally mechanical: it records every Python class, module function, and class method so code reviews can track ownership and refactor scope.",
        "",
        "## Summary",
        "",
        "| Area | Python files | Classes | Module functions | Methods | Lines |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    summaries = []
    for source_dir in SOURCE_DIRS:
        files = sorted((ROOT / source_dir).rglob("*.py"))
        files = [path for path in files if "__pycache__" not in path.parts]
        summary = summarize_files(files)
        summaries.append((source_dir, files, summary))
        sections.append(
            f"| `{source_dir}/` | {len(files)} | {summary['classes']} | {summary['functions']} | {summary['methods']} | {summary['lines']} |"
        )
    sections.extend(["", "## Modules", ""])
    for source_dir, files, _summary in summaries:
        sections.extend([f"### `{source_dir}/`", ""])
        for path in files:
            symbols = module_symbols(path)
            if not symbols:
                continue
            rel = path.relative_to(ROOT)
            line_count = len(path.read_text(encoding="utf-8").splitlines())
            sections.extend(
                [
                    f"#### `{rel}`",
                    "",
                    f"Lines: {line_count}",
                    "",
                    "| Kind | Name | Line | Signature |",
                    "| --- | --- | ---: | --- |",
                ]
            )
            for symbol in symbols:
                sections.append(
                    f"| {symbol.kind} | `{symbol.name}` | {symbol.line} | `{escape_table(symbol.signature)}` |"
                )
            sections.append("")
    sections.extend(
        [
            "## Review Notes",
            "",
            "- Public API handlers should remain thin and delegate to workflows or services.",
            "- `app/services/research.py` and `app/services/stock_insights.py` are compatibility facades; keep new behavior in domain modules and re-export only stable public builders.",
            "- `static/styles.css` is now an import manifest for `static/css/*`; tests are split by domain, with route-level API contract tests still a useful next step.",
            "- When a function changes behavior, update the relevant SRS requirement, design section, and tests before regenerating this inventory.",
            "",
        ]
    )
    return "\n".join(sections)


def summarize_files(files: list[Path]) -> dict[str, int]:
    summary = {"classes": 0, "functions": 0, "methods": 0, "lines": 0}
    for path in files:
        text = path.read_text(encoding="utf-8")
        summary["lines"] += len(text.splitlines())
        tree = ast.parse(text)
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                summary["classes"] += 1
                summary["methods"] += sum(isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) for item in node.body)
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                summary["functions"] += 1
    return summary


def module_symbols(path: Path) -> list[Symbol]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    symbols: list[Symbol] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            symbols.append(Symbol("class", node.name, node.lineno, class_signature(node)))
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    symbols.append(Symbol("method", f"{node.name}.{item.name}", item.lineno, function_signature(item)))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            symbols.append(Symbol("async function" if isinstance(node, ast.AsyncFunctionDef) else "function", node.name, node.lineno, function_signature(node)))
    return symbols


def class_signature(node: ast.ClassDef) -> str:
    bases = [ast.unparse(base) for base in node.bases]
    return f"class {node.name}({', '.join(bases)})" if bases else f"class {node.name}"


def function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    args = ast.unparse(node.args)
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{prefix} {node.name}({args}){returns}"


def escape_table(value: str) -> str:
    return value.replace("|", "\\|")


if __name__ == "__main__":
    main()
