from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "FUNCTION_INVENTORY.md"
SOURCE_DIRS = ("app", "tests", "tools")
PRODUCTION_SOURCE_DIRS = ("app", "tools")
MAX_PRODUCTION_FUNCTION_LINES = 60
MAX_PRODUCTION_FUNCTION_BRANCHES = 12
BRANCH_NODE_TYPES = (
    ast.If,
    ast.For,
    ast.AsyncFor,
    ast.While,
    ast.Try,
    ast.ExceptHandler,
    ast.BoolOp,
    ast.IfExp,
    ast.Match,
    ast.comprehension,
)


@dataclass(frozen=True)
class Symbol:
    kind: str
    name: str
    line: int
    signature: str


@dataclass(frozen=True)
class FunctionMetric:
    path: Path
    qualified_name: str
    line: int
    lines: int
    branches: int


@dataclass(frozen=True)
class SourceInventory:
    name: str
    files: list[Path]
    summary: dict[str, int]
    function_metrics: list[FunctionMetric]


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_inventory(), encoding="utf-8")


def build_inventory() -> str:
    sources = collect_source_inventories()
    sections = render_intro()
    sections.extend(render_summary(sources))
    sections.extend(render_code_health(sources))
    sections.extend(render_modules(sources))
    sections.extend(render_review_notes())
    return "\n".join(sections)


def collect_source_inventories() -> list[SourceInventory]:
    sources: list[SourceInventory] = []
    for source_dir in SOURCE_DIRS:
        files = python_files(source_dir)
        sources.append(SourceInventory(source_dir, files, summarize_files(files), collect_function_metrics(files)))
    return sources


def python_files(source_dir: str) -> list[Path]:
    files = sorted((ROOT / source_dir).rglob("*.py"))
    return [path for path in files if "__pycache__" not in path.parts]


def render_intro() -> list[str]:
    return [
        "# Function Inventory",
        "",
        "This file is generated by `$PYTHON tools/architecture_inventory.py`.",
        "It is intentionally mechanical: it records every Python class, module function, and class method so code reviews can track ownership and refactor scope.",
        "",
    ]


def render_summary(sources: list[SourceInventory]) -> list[str]:
    sections = [
        "## Summary",
        "",
        "| Area | Python files | Classes | Module functions | Methods | Lines |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for source in sources:
        sections.append(
            f"| `{source.name}/` | {len(source.files)} | {source.summary['classes']} | {source.summary['functions']} | {source.summary['methods']} | {source.summary['lines']} |"
        )
    return sections


def render_code_health(sources: list[SourceInventory]) -> list[str]:
    sections = [
        "",
        "## Python Function Health",
        "",
        "Branch points count `if`, loops, `try/except`, boolean operators, ternaries, `match`, and comprehensions inside each function.",
        "",
        "| Area | Longest function | Branchiest function |",
        "| --- | --- | --- |",
    ]
    for source in sources:
        longest = max(source.function_metrics, key=lambda item: (item.lines, item.branches, item.path.as_posix(), item.qualified_name), default=None)
        branchiest = max(source.function_metrics, key=lambda item: (item.branches, item.lines, item.path.as_posix(), item.qualified_name), default=None)
        sections.append(f"| `{source.name}/` | {metric_summary(longest, 'lines')} | {metric_summary(branchiest, 'branches')} |")
    return sections


def metric_summary(metric: FunctionMetric | None, field: str) -> str:
    if metric is None:
        return "None"
    value = metric.lines if field == "lines" else metric.branches
    label = "lines" if field == "lines" else "branches"
    return f"{value} {label}: `{metric.path.relative_to(ROOT)}:{metric.qualified_name}`"


def render_modules(sources: list[SourceInventory]) -> list[str]:
    sections = ["", "## Modules", ""]
    for source in sources:
        sections.extend(render_source_modules(source))
    return sections


def render_source_modules(source: SourceInventory) -> list[str]:
    sections = [f"### `{source.name}/`", ""]
    for path in source.files:
        sections.extend(render_module(path))
    return sections


def render_module(path: Path) -> list[str]:
    symbols = module_symbols(path)
    if not symbols:
        return []
    rel = path.relative_to(ROOT)
    line_count = len(path.read_text(encoding="utf-8").splitlines())
    sections = [
        f"#### `{rel}`",
        "",
        f"Lines: {line_count}",
        "",
        "| Kind | Name | Line | Signature |",
        "| --- | --- | ---: | --- |",
    ]
    for symbol in symbols:
        sections.append(f"| {symbol.kind} | `{symbol.name}` | {symbol.line} | `{escape_table(symbol.signature)}` |")
    sections.append("")
    return sections


def render_review_notes() -> list[str]:
    return [
        "## Review Notes",
        "",
        "- Public API handlers should remain thin and delegate to workflows or services.",
        "- `app/services/research.py` and `app/services/stock_insights.py` are compatibility facades; keep new behavior in domain modules and re-export only stable public builders.",
        "- `static/styles.css` is now an import manifest for `static/css/*`; tests are split by domain, with route-level API contract tests still a useful next step.",
        f"- Production Python functions in `app/` and `tools/` are test-guarded at <= {MAX_PRODUCTION_FUNCTION_LINES} lines and <= {MAX_PRODUCTION_FUNCTION_BRANCHES} branch points; split staged helpers before crossing those limits.",
        "- When a function changes behavior, update the relevant SRS requirement, design section, and tests before regenerating this inventory.",
        "",
    ]


def summarize_files(files: list[Path]) -> dict[str, int]:
    summary = {"classes": 0, "functions": 0, "methods": 0, "lines": 0}
    for path in files:
        text = path.read_text(encoding="utf-8")
        summary["lines"] += len(text.splitlines())
        tree = ast.parse(text)
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                summary["classes"] += 1
                summary["methods"] += sum(isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)) for item in node.body)
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                summary["functions"] += 1
    return summary


def collect_function_metrics(files: list[Path]) -> list[FunctionMetric]:
    metrics: list[FunctionMetric] = []
    for path in files:
        tree = ast.parse(path.read_text(encoding="utf-8"))
        metrics.extend(module_function_metrics(path, tree))
    return metrics


def module_function_metrics(path: Path, tree: ast.AST) -> list[FunctionMetric]:
    metrics: list[FunctionMetric] = []
    stack: list[str] = []

    class MetricVisitor(ast.NodeVisitor):
        def visit_ClassDef(self, node: ast.ClassDef) -> None:
            stack.append(node.name)
            self.generic_visit(node)
            stack.pop()

        def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
            self._visit_function(node)

        def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
            self._visit_function(node)

        def _visit_function(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
            metrics.append(function_metric(path, stack, node))
            stack.append(node.name)
            self.generic_visit(node)
            stack.pop()

    MetricVisitor().visit(tree)
    return metrics


def function_metric(path: Path, stack: list[str], node: ast.FunctionDef | ast.AsyncFunctionDef) -> FunctionMetric:
    end_line = node.end_lineno or node.lineno
    return FunctionMetric(
        path=path,
        qualified_name=".".join([*stack, node.name]),
        line=node.lineno,
        lines=end_line - node.lineno + 1,
        branches=count_branch_points(node),
    )


def count_branch_points(root: ast.FunctionDef | ast.AsyncFunctionDef) -> int:
    class BranchCounter(ast.NodeVisitor):
        def __init__(self) -> None:
            self.count = 0

        def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
            if node is root:
                self.generic_visit(node)

        def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
            if node is root:
                self.generic_visit(node)

        def visit_ClassDef(self, node: ast.ClassDef) -> None:
            return

        def generic_visit(self, node: ast.AST) -> None:
            if isinstance(node, BRANCH_NODE_TYPES):
                self.count += 1
            super().generic_visit(node)

    counter = BranchCounter()
    counter.visit(root)
    return counter.count


def module_symbols(path: Path) -> list[Symbol]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    symbols: list[Symbol] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            symbols.append(Symbol("class", node.name, node.lineno, class_signature(node)))
            for item in node.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    symbols.append(Symbol("method", f"{node.name}.{item.name}", item.lineno, function_signature(item)))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            symbols.append(Symbol("async function" if isinstance(node, ast.AsyncFunctionDef) else "function", node.name, node.lineno, function_signature(node)))
    return symbols


def class_signature(node: ast.ClassDef) -> str:
    bases = [ast.unparse(base) for base in node.bases]
    return f"class {node.name}({', '.join(bases)})" if bases else f"class {node.name}"


def function_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    args = ast.unparse(node.args)
    returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
    return f"{prefix} {node.name}({args}){returns}"


def escape_table(value: str) -> str:
    return value.replace("|", "\\|")


if __name__ == "__main__":
    main()
